// ARK Server Configuration AI — Preset Templates
// Each preset is a map of setting_id → value
// Presets are the starting point; the engine adjusts from here.

export const PRESETS = {

    // ─── BEGINNER PvE ─────────────────────────────────────────────────────────
    beginner_pve: {
        label: "Beginner PvE",
        description: "Relaxed settings for new players. Reduced grind, faster progression, forgiving mechanics.",
        // Difficulty
        difficulty_offset: 0.2,
        override_official_difficulty: 1.0,
        dino_damage_multiplier: 0.6,
        player_damage_multiplier: 1.5,
        dino_resistance_multiplier: 0.8,
        player_resistance_multiplier: 0.5,
        // XP
        xp_multiplier: 3.0,
        kill_xp_multiplier: 3.0,
        harvest_xp_multiplier: 3.0,
        craft_xp_multiplier: 3.0,
        generic_xp_multiplier: 3.0,
        special_xp_multiplier: 3.0,
        // Taming
        taming_speed_multiplier: 5.0,
        dino_character_food_drain_multiplier: 0.5,
        wild_dino_torpor_drain_multiplier: 0.5,
        wild_dino_character_food_drain_multiplier: 0.5,
        // Harvesting
        harvest_amount_multiplier: 3.0,
        resource_respawn_period_multiplier: 0.5,
        harvest_health_multiplier: 0.5,
        // Breeding
        baby_mature_speed_multiplier: 20.0,
        egg_hatch_speed_multiplier: 10.0,
        baby_food_consumption_speed_multiplier: 0.25,
        baby_imprinting_stat_scale_multiplier: 1.0,
        baby_cuddle_interval_multiplier: 0.1,
        baby_cuddle_grace_period_multiplier: 5.0,
        mating_interval_multiplier: 0.1,
        mating_speed_multiplier: 2.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.5,
        player_character_food_drain_multiplier: 0.5,
        player_character_stamina_drain_multiplier: 0.5,
        player_character_health_recovery_multiplier: 2.0,
        dino_character_health_recovery_multiplier: 2.0,
        item_stack_size_multiplier: 5.0,
        spoiling_time_multiplier: 3.0,
        global_corpse_decomposition_time_multiplier: 3.0,
        fuel_consumption_interval_multiplier: 5.0,
        day_time_speed_scale: 0.5,
        night_time_speed_scale: 3.0,
        max_tamed_dinos: 5000,
        show_map_player_location: true,
        allow_third_person_player: true,
        allow_flyer_carry_pve: true,
        // Loot
        supply_crate_loot_quality_multiplier: 2.0,
        fishing_loot_quality_multiplier: 2.0,
        crafting_skill_bonus_multiplier: 2.0,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 3600.0,
        pve_structure_decay_period_multiplier: 4.0,
        // PvP flags (off for PvE)
        server_pvp: false,
    },

    // ─── INTERMEDIATE PvE ─────────────────────────────────────────────────────
    intermediate_pve: {
        label: "Intermediate PvE",
        description: "Balanced settings. Moderate boosts to reduce tedium while keeping challenge.",
        // Difficulty
        difficulty_offset: 0.5,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.2,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 0.8,
        // XP
        xp_multiplier: 1.5,
        kill_xp_multiplier: 1.5,
        harvest_xp_multiplier: 1.5,
        craft_xp_multiplier: 1.5,
        generic_xp_multiplier: 1.5,
        special_xp_multiplier: 1.5,
        // Taming
        taming_speed_multiplier: 3.0,
        dino_character_food_drain_multiplier: 0.7,
        wild_dino_torpor_drain_multiplier: 0.7,
        wild_dino_character_food_drain_multiplier: 0.7,
        // Harvesting
        harvest_amount_multiplier: 2.0,
        resource_respawn_period_multiplier: 0.7,
        harvest_health_multiplier: 0.7,
        // Breeding
        baby_mature_speed_multiplier: 10.0,
        egg_hatch_speed_multiplier: 5.0,
        baby_food_consumption_speed_multiplier: 0.5,
        baby_imprinting_stat_scale_multiplier: 1.0,
        baby_cuddle_interval_multiplier: 0.2,
        baby_cuddle_grace_period_multiplier: 3.0,
        mating_interval_multiplier: 0.3,
        mating_speed_multiplier: 1.5,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.7,
        player_character_food_drain_multiplier: 0.7,
        player_character_stamina_drain_multiplier: 0.7,
        player_character_health_recovery_multiplier: 1.5,
        dino_character_health_recovery_multiplier: 1.5,
        item_stack_size_multiplier: 3.0,
        spoiling_time_multiplier: 2.0,
        global_corpse_decomposition_time_multiplier: 2.0,
        fuel_consumption_interval_multiplier: 3.0,
        day_time_speed_scale: 0.7,
        night_time_speed_scale: 2.0,
        max_tamed_dinos: 5000,
        show_map_player_location: true,
        allow_third_person_player: true,
        allow_flyer_carry_pve: true,
        // Loot
        supply_crate_loot_quality_multiplier: 1.5,
        fishing_loot_quality_multiplier: 1.5,
        crafting_skill_bonus_multiplier: 1.5,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 1800.0,
        pve_structure_decay_period_multiplier: 2.0,
        // PvP flags
        server_pvp: false,
    },

    // ─── VETERAN PvE ──────────────────────────────────────────────────────────
    veteran_pve: {
        label: "Veteran PvE",
        description: "Near-vanilla with small quality-of-life improvements. Full challenge preserved.",
        // Difficulty
        difficulty_offset: 1.0,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.0,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 1.0,
        kill_xp_multiplier: 1.0,
        harvest_xp_multiplier: 1.0,
        craft_xp_multiplier: 1.0,
        generic_xp_multiplier: 1.0,
        special_xp_multiplier: 1.0,
        // Taming
        taming_speed_multiplier: 1.5,
        dino_character_food_drain_multiplier: 0.9,
        wild_dino_torpor_drain_multiplier: 0.9,
        wild_dino_character_food_drain_multiplier: 0.9,
        // Harvesting
        harvest_amount_multiplier: 1.5,
        resource_respawn_period_multiplier: 0.9,
        harvest_health_multiplier: 1.0,
        // Breeding
        baby_mature_speed_multiplier: 3.0,
        egg_hatch_speed_multiplier: 2.0,
        baby_food_consumption_speed_multiplier: 0.75,
        baby_imprinting_stat_scale_multiplier: 1.0,
        baby_cuddle_interval_multiplier: 0.5,
        baby_cuddle_grace_period_multiplier: 2.0,
        mating_interval_multiplier: 0.5,
        mating_speed_multiplier: 1.0,
        allow_anyone_baby_imprint_cuddle: false,
        // QoL
        player_character_water_drain_multiplier: 0.9,
        player_character_food_drain_multiplier: 0.9,
        player_character_stamina_drain_multiplier: 0.9,
        player_character_health_recovery_multiplier: 1.0,
        dino_character_health_recovery_multiplier: 1.0,
        item_stack_size_multiplier: 2.0,
        spoiling_time_multiplier: 1.5,
        global_corpse_decomposition_time_multiplier: 1.5,
        fuel_consumption_interval_multiplier: 2.0,
        day_time_speed_scale: 1.0,
        night_time_speed_scale: 1.0,
        max_tamed_dinos: 5000,
        show_map_player_location: false,
        allow_third_person_player: true,
        allow_flyer_carry_pve: false,
        // Loot
        supply_crate_loot_quality_multiplier: 1.0,
        fishing_loot_quality_multiplier: 1.0,
        crafting_skill_bonus_multiplier: 1.0,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 30.0,
        pve_structure_decay_period_multiplier: 1.0,
        // PvP flags
        server_pvp: false,
    },

    // ─── BEGINNER PvP ─────────────────────────────────────────────────────────
    beginner_pvp: {
        label: "Beginner PvP",
        description: "Casual PvP with fast progression. Reduced offline raiding impact.",
        // Difficulty
        difficulty_offset: 0.2,
        override_official_difficulty: 1.0,
        dino_damage_multiplier: 0.8,
        player_damage_multiplier: 1.2,
        dino_resistance_multiplier: 0.8,
        player_resistance_multiplier: 0.7,
        // XP
        xp_multiplier: 4.0,
        kill_xp_multiplier: 4.0,
        harvest_xp_multiplier: 4.0,
        craft_xp_multiplier: 4.0,
        generic_xp_multiplier: 4.0,
        special_xp_multiplier: 4.0,
        // Taming
        taming_speed_multiplier: 8.0,
        dino_character_food_drain_multiplier: 0.4,
        wild_dino_torpor_drain_multiplier: 0.4,
        wild_dino_character_food_drain_multiplier: 0.4,
        // Harvesting
        harvest_amount_multiplier: 5.0,
        resource_respawn_period_multiplier: 0.3,
        harvest_health_multiplier: 0.3,
        // Breeding
        baby_mature_speed_multiplier: 30.0,
        egg_hatch_speed_multiplier: 15.0,
        baby_food_consumption_speed_multiplier: 0.1,
        baby_imprinting_stat_scale_multiplier: 1.0,
        baby_cuddle_interval_multiplier: 0.05,
        baby_cuddle_grace_period_multiplier: 10.0,
        mating_interval_multiplier: 0.05,
        mating_speed_multiplier: 3.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.3,
        player_character_food_drain_multiplier: 0.3,
        player_character_stamina_drain_multiplier: 0.3,
        player_character_health_recovery_multiplier: 3.0,
        dino_character_health_recovery_multiplier: 3.0,
        item_stack_size_multiplier: 10.0,
        spoiling_time_multiplier: 5.0,
        global_corpse_decomposition_time_multiplier: 5.0,
        fuel_consumption_interval_multiplier: 10.0,
        day_time_speed_scale: 0.5,
        night_time_speed_scale: 3.0,
        max_tamed_dinos: 5000,
        show_map_player_location: false,
        allow_third_person_player: true,
        allow_flyer_carry_pve: false,
        // Loot
        supply_crate_loot_quality_multiplier: 3.0,
        fishing_loot_quality_multiplier: 3.0,
        crafting_skill_bonus_multiplier: 3.0,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 600.0,
        pve_structure_decay_period_multiplier: 1.0,
        // PvP
        server_pvp: true,
        structure_damage_multiplier: 1.0,
        structure_resistance_multiplier: 1.0,
        max_tribe_size: 6,
        pvp_dino_decay: true,
        pvp_structure_decay: true,
    },

    // ─── INTERMEDIATE PvP ─────────────────────────────────────────────────────
    intermediate_pvp: {
        label: "Intermediate PvP",
        description: "Boosted PvP server. Fast enough to stay competitive, hard enough to matter.",
        // Difficulty
        difficulty_offset: 0.5,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.0,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 2.0,
        kill_xp_multiplier: 2.0,
        harvest_xp_multiplier: 2.0,
        craft_xp_multiplier: 2.0,
        generic_xp_multiplier: 2.0,
        special_xp_multiplier: 2.0,
        // Taming
        taming_speed_multiplier: 5.0,
        dino_character_food_drain_multiplier: 0.5,
        wild_dino_torpor_drain_multiplier: 0.5,
        wild_dino_character_food_drain_multiplier: 0.5,
        // Harvesting
        harvest_amount_multiplier: 3.0,
        resource_respawn_period_multiplier: 0.5,
        harvest_health_multiplier: 0.5,
        // Breeding
        baby_mature_speed_multiplier: 20.0,
        egg_hatch_speed_multiplier: 10.0,
        baby_food_consumption_speed_multiplier: 0.2,
        baby_imprinting_stat_scale_multiplier: 1.0,
        baby_cuddle_interval_multiplier: 0.1,
        baby_cuddle_grace_period_multiplier: 5.0,
        mating_interval_multiplier: 0.1,
        mating_speed_multiplier: 2.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.5,
        player_character_food_drain_multiplier: 0.5,
        player_character_stamina_drain_multiplier: 0.5,
        player_character_health_recovery_multiplier: 2.0,
        dino_character_health_recovery_multiplier: 2.0,
        item_stack_size_multiplier: 5.0,
        spoiling_time_multiplier: 3.0,
        global_corpse_decomposition_time_multiplier: 3.0,
        fuel_consumption_interval_multiplier: 5.0,
        day_time_speed_scale: 0.7,
        night_time_speed_scale: 2.0,
        max_tamed_dinos: 5000,
        show_map_player_location: false,
        allow_third_person_player: true,
        allow_flyer_carry_pve: false,
        // Loot
        supply_crate_loot_quality_multiplier: 2.0,
        fishing_loot_quality_multiplier: 2.0,
        crafting_skill_bonus_multiplier: 2.0,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 300.0,
        pve_structure_decay_period_multiplier: 1.0,
        // PvP
        server_pvp: true,
        structure_damage_multiplier: 1.0,
        structure_resistance_multiplier: 1.0,
        max_tribe_size: 10,
        pvp_dino_decay: true,
        pvp_structure_decay: true,
    },

    // ─── VETERAN PvP ──────────────────────────────────────────────────────────
    veteran_pvp: {
        label: "Veteran PvP",
        description: "Hardcore PvP. Near-official rates. Only for experienced players.",
        // Difficulty
        difficulty_offset: 1.0,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.0,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 1.0,
        kill_xp_multiplier: 1.0,
        harvest_xp_multiplier: 1.0,
        craft_xp_multiplier: 1.0,
        generic_xp_multiplier: 1.0,
        special_xp_multiplier: 1.0,
        // Taming
        taming_speed_multiplier: 2.0,
        dino_character_food_drain_multiplier: 0.8,
        wild_dino_torpor_drain_multiplier: 0.8,
        wild_dino_character_food_drain_multiplier: 0.8,
        // Harvesting
        harvest_amount_multiplier: 2.0,
        resource_respawn_period_multiplier: 0.7,
        harvest_health_multiplier: 0.7,
        // Breeding
        baby_mature_speed_multiplier: 5.0,
        egg_hatch_speed_multiplier: 3.0,
        baby_food_consumption_speed_multiplier: 0.5,
        baby_imprinting_stat_scale_multiplier: 1.0,
        baby_cuddle_interval_multiplier: 0.3,
        baby_cuddle_grace_period_multiplier: 2.0,
        mating_interval_multiplier: 0.3,
        mating_speed_multiplier: 1.5,
        allow_anyone_baby_imprint_cuddle: false,
        // QoL
        player_character_water_drain_multiplier: 0.8,
        player_character_food_drain_multiplier: 0.8,
        player_character_stamina_drain_multiplier: 0.8,
        player_character_health_recovery_multiplier: 1.0,
        dino_character_health_recovery_multiplier: 1.0,
        item_stack_size_multiplier: 2.0,
        spoiling_time_multiplier: 2.0,
        global_corpse_decomposition_time_multiplier: 2.0,
        fuel_consumption_interval_multiplier: 2.0,
        day_time_speed_scale: 1.0,
        night_time_speed_scale: 1.0,
        max_tamed_dinos: 5000,
        show_map_player_location: false,
        allow_third_person_player: true,
        allow_flyer_carry_pve: false,
        // Loot
        supply_crate_loot_quality_multiplier: 1.0,
        fishing_loot_quality_multiplier: 1.0,
        crafting_skill_bonus_multiplier: 1.0,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 30.0,
        pve_structure_decay_period_multiplier: 1.0,
        // PvP
        server_pvp: true,
        structure_damage_multiplier: 1.0,
        structure_resistance_multiplier: 1.0,
        max_tribe_size: 25,
        pvp_dino_decay: true,
        pvp_structure_decay: true,
    },

    // ─── PvE BEGINNER ─────────────────────────────────────────────────────────
    pve_beginner: {
        label: "PvE Beginner + Instant Breeding",
        description: "2x Farming, 10x Taming, Instant Breeding, 0.5 Wild Dino Difficulty. Perfekt für Einsteiger — einfache Zähmung, schnelles Breeding, entspanntes Farmen.",
        tags: ["2x Farming", "10x Taming", "Instant Breeding", "0.5 Wild Dino Difficulty"],
        // Difficulty — max level 150, wilds are 0.5 strength via PerLevelStats
        difficulty_offset: 1.0,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.2,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 1.3,
        kill_xp_multiplier: 1.0,
        harvest_xp_multiplier: 1.0,
        craft_xp_multiplier: 1.0,
        generic_xp_multiplier: 1.0,
        special_xp_multiplier: 1.0,
        override_max_experience_points_player: 0,
        // Taming — 10x
        taming_speed_multiplier: 10.0,
        tamed_dino_damage_multiplier: 2.0,
        tamed_dino_resistance_multiplier: 1.0,
        wild_dino_torpor_drain_multiplier: 1.0,
        wild_dino_character_food_drain_multiplier: 1.0,
        tamed_dino_torpor_drain_multiplier: 1.0,
        passive_tame_interval_multiplier: 1.0,
        disable_dino_riding: false,
        disable_dino_taming: false,
        use_tame_limit_for_structures_only: false,
        max_tamed_dinos: 8000,
        // Harvesting — 2x
        harvest_amount_multiplier: 2.0,
        harvest_health_multiplier: 2.0,
        resource_respawn_period_multiplier: 0.1,
        resource_no_replenish_radius_players: 0.3,
        resource_no_replenish_radius_structures: 0.4,
        player_harvesting_damage_multiplier: 1.0,
        dino_harvesting_damage_multiplier: 3.2,
        // Breeding — Instant (same as real server)
        mating_interval_multiplier: 0.0001,
        mating_speed_multiplier: 40.0,
        lay_egg_interval_multiplier: 1.0,
        egg_hatch_speed_multiplier: 240.0,
        baby_mature_speed_multiplier: 480.0,
        baby_cuddle_interval_multiplier: 0.1,
        baby_imprinting_stat_scale_multiplier: 5.0,
        baby_imprint_amount_multiplier: 10.0,
        baby_food_consumption_speed_multiplier: 1.0,
        baby_cuddle_grace_period_multiplier: 5.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.2,
        player_character_food_drain_multiplier: 0.2,
        player_character_stamina_drain_multiplier: 1.0,
        player_character_health_recovery_multiplier: 1.0,
        dino_character_health_recovery_multiplier: 1.0,
        item_stack_size_multiplier: 1.0,
        global_spoiling_time_multiplier: 1.0,
        global_item_decomposition_time_multiplier: 1.0,
        global_corpse_decomposition_time_multiplier: 1.0,
        base_temperature_multiplier: 0.475,
        day_cycle_speed_scale: 1.0,
        day_time_speed_scale: 1.6,
        night_time_speed_scale: 3.0,
        kick_idle_players_period: 3600,
        show_map_player_location: true,
        allow_third_person_player: true,
        server_crosshair: true,
        global_voice_chat: false,
        proximity_chat: false,
        // Loot
        supply_crate_loot_quality_multiplier: 3.0,
        fishing_loot_quality_multiplier: 3.0,
        crafting_skill_bonus_multiplier: 1.0,
        allow_custom_recipes: true,
        custom_recipe_effectiveness_multiplier: 1.0,
        custom_recipe_skill_multiplier: 1.0,
        disable_loot_crates: false,
        random_supply_crate_points: false,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 3600.0,
        disable_structure_placement_collision: false,
        allow_platform_saddle_multi_floors: false,
        ignore_structures_prevention_volumes: true,
        genesis_use_structures_prevention_volumes: true,
        fast_decay_interval: 43200,
        structure_damage_repair_cooldown: 180,
        allow_cave_building_pve: false,
        allow_flyer_carry_pve_gus: false,
        disable_structure_decay_pve: false,
        pve_structure_decay_destruction_period: 1.0,
        max_structures_in_range: 6700,
        // Tribe & PvE
        server_pvp: false,
        max_tribe_size: 70,
        max_tribe_logs: 1,
        max_alliances_per_tribe: 10,
        disable_friendly_fire: false,
        pve_disable_friendly_fire: false,
        pve_allow_tribe_war: true,
        pve_allow_tribe_war_cancel: false,
        // Turrets
        limit_turrets_in_range: true,
        limit_turrets_range: 10000,
        limit_turrets_num: 100,
        hard_limit_turrets_in_range: true,
        passive_defenses_damage_riderless_dinos: false,
        dino_turret_damage_multiplier: 1.0,
        // Transfers
        no_tribute_downloads: false,
        prevent_download_survivors: false,
        prevent_download_items: false,
        prevent_download_dinos: false,
        // Genesis
        disable_genesis_missions: false,
        show_creative_mode: false,
        auto_unlock_all_engrams: false,
        // PerLevelStats — Player (all 1.0)
        per_level_stats_player_0: 1.0, per_level_stats_player_1: 1.0, per_level_stats_player_2: 1.0,
        per_level_stats_player_3: 1.0, per_level_stats_player_4: 1.0, per_level_stats_player_5: 1.0,
        per_level_stats_player_6: 1.0, per_level_stats_player_7: 1.0, per_level_stats_player_8: 1.0,
        per_level_stats_player_9: 1.0, per_level_stats_player_10: 1.0, per_level_stats_player_11: 1.0,
        // PerLevelStats — Wild Dino (0.5 = 0.5 Difficulty)
        per_level_stats_dino_wild_0: 0.5, per_level_stats_dino_wild_1: 0.5, per_level_stats_dino_wild_2: 0.5,
        per_level_stats_dino_wild_3: 0.5, per_level_stats_dino_wild_4: 0.5, per_level_stats_dino_wild_5: 0.5,
        per_level_stats_dino_wild_6: 0.5, per_level_stats_dino_wild_7: 0.5, per_level_stats_dino_wild_8: 0.5,
        per_level_stats_dino_wild_9: 0.5,
        // PerLevelStats — Tamed Dino
        per_level_stats_dino_tamed_0: 0.2, per_level_stats_dino_tamed_1: 1.0, per_level_stats_dino_tamed_2: 1.0,
        per_level_stats_dino_tamed_3: 1.0, per_level_stats_dino_tamed_4: 1.0, per_level_stats_dino_tamed_5: 1.0,
        per_level_stats_dino_tamed_6: 1.0, per_level_stats_dino_tamed_7: 1.0, per_level_stats_dino_tamed_8: 0.17,
        per_level_stats_dino_tamed_9: 1.0,
        // PerLevelStats — Tamed Add
        per_level_stats_tamed_add_0: 0.14, per_level_stats_tamed_add_1: 1.0, per_level_stats_tamed_add_2: 1.0,
        per_level_stats_tamed_add_3: 1.0, per_level_stats_tamed_add_4: 1.0, per_level_stats_tamed_add_5: 1.0,
        per_level_stats_tamed_add_6: 1.0, per_level_stats_tamed_add_7: 1.0, per_level_stats_tamed_add_8: 0.14,
        per_level_stats_tamed_add_9: 1.0,
        // PerLevelStats — Tamed Affinity
        per_level_stats_dino_tamed_affinity_0: 0.44, per_level_stats_dino_tamed_affinity_1: 1.0,
        per_level_stats_dino_tamed_affinity_2: 1.0, per_level_stats_dino_tamed_affinity_3: 1.0,
        per_level_stats_dino_tamed_affinity_4: 1.0, per_level_stats_dino_tamed_affinity_5: 1.0,
        per_level_stats_dino_tamed_affinity_6: 1.0, per_level_stats_dino_tamed_affinity_7: 1.0,
        per_level_stats_dino_tamed_affinity_8: 0.44, per_level_stats_dino_tamed_affinity_9: 1.0,
    },

    // ─── PvE STANDARD ─────────────────────────────────────────────────────────
    pve_standard: {
        label: "PvE Standard + Instant Breeding",
        description: "Instant Breeding, 10x Taming, 2x Farming, vanilla wild dino stats. Für erfahrenere Spieler die Herausforderung beim Zähmen und Kämpfen suchen.",
        tags: ["2x Farming", "5x Taming", "Instant Breeding", "Vanilla Wild Dinos"],
        // Difficulty — vanilla wild dino stats, vanilla damage
        difficulty_offset: 1.0,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.0,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 1.3,
        kill_xp_multiplier: 1.0,
        harvest_xp_multiplier: 1.0,
        craft_xp_multiplier: 1.0,
        generic_xp_multiplier: 1.0,
        special_xp_multiplier: 1.0,
        override_max_experience_points_player: 0,
        // Taming — 10x, vanilla damage
        taming_speed_multiplier: 10.0,
        tamed_dino_damage_multiplier: 1.0,
        tamed_dino_resistance_multiplier: 1.0,
        wild_dino_torpor_drain_multiplier: 1.0,
        wild_dino_character_food_drain_multiplier: 1.0,
        tamed_dino_torpor_drain_multiplier: 1.0,
        passive_tame_interval_multiplier: 1.0,
        disable_dino_riding: false,
        disable_dino_taming: false,
        use_tame_limit_for_structures_only: false,
        max_tamed_dinos: 8000,
        // Harvesting — 2x
        harvest_amount_multiplier: 2.0,
        harvest_health_multiplier: 2.0,
        resource_respawn_period_multiplier: 0.1,
        resource_no_replenish_radius_players: 0.3,
        resource_no_replenish_radius_structures: 0.4,
        player_harvesting_damage_multiplier: 1.0,
        dino_harvesting_damage_multiplier: 3.2,
        // Breeding — Instant (same as pve_beginner)
        mating_interval_multiplier: 0.0001,
        mating_speed_multiplier: 40.0,
        lay_egg_interval_multiplier: 1.0,
        egg_hatch_speed_multiplier: 240.0,
        baby_mature_speed_multiplier: 480.0,
        baby_cuddle_interval_multiplier: 0.1,
        baby_imprinting_stat_scale_multiplier: 5.0,
        baby_imprint_amount_multiplier: 10.0,
        baby_food_consumption_speed_multiplier: 1.0,
        baby_cuddle_grace_period_multiplier: 5.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.2,
        player_character_food_drain_multiplier: 0.2,
        player_character_stamina_drain_multiplier: 1.0,
        player_character_health_recovery_multiplier: 1.0,
        dino_character_health_recovery_multiplier: 1.0,
        item_stack_size_multiplier: 1.0,
        global_spoiling_time_multiplier: 1.0,
        global_item_decomposition_time_multiplier: 1.0,
        global_corpse_decomposition_time_multiplier: 1.0,
        base_temperature_multiplier: 0.475,
        day_cycle_speed_scale: 1.0,
        day_time_speed_scale: 1.6,
        night_time_speed_scale: 3.0,
        kick_idle_players_period: 3600,
        show_map_player_location: true,
        allow_third_person_player: true,
        server_crosshair: true,
        global_voice_chat: false,
        proximity_chat: false,
        // Loot — 2.5x
        supply_crate_loot_quality_multiplier: 2.5,
        fishing_loot_quality_multiplier: 2.5,
        crafting_skill_bonus_multiplier: 1.0,
        allow_custom_recipes: true,
        custom_recipe_effectiveness_multiplier: 1.0,
        custom_recipe_skill_multiplier: 1.0,
        disable_loot_crates: false,
        random_supply_crate_points: false,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 3600.0,
        disable_structure_placement_collision: false,
        allow_platform_saddle_multi_floors: false,
        ignore_structures_prevention_volumes: true,
        genesis_use_structures_prevention_volumes: true,
        fast_decay_interval: 43200,
        structure_damage_repair_cooldown: 180,
        allow_cave_building_pve: false,
        allow_flyer_carry_pve_gus: false,
        disable_structure_decay_pve: false,
        pve_structure_decay_destruction_period: 1.0,
        max_structures_in_range: 6700,
        // Tribe & PvE
        server_pvp: false,
        max_tribe_size: 70,
        max_tribe_logs: 1,
        max_alliances_per_tribe: 10,
        disable_friendly_fire: false,
        pve_disable_friendly_fire: false,
        pve_allow_tribe_war: true,
        pve_allow_tribe_war_cancel: false,
        // Turrets
        limit_turrets_in_range: true,
        limit_turrets_range: 10000,
        limit_turrets_num: 100,
        hard_limit_turrets_in_range: true,
        passive_defenses_damage_riderless_dinos: false,
        dino_turret_damage_multiplier: 1.0,
        // Transfers
        no_tribute_downloads: false,
        prevent_download_survivors: false,
        prevent_download_items: false,
        prevent_download_dinos: false,
        // Genesis
        disable_genesis_missions: false,
        show_creative_mode: false,
        auto_unlock_all_engrams: false,
        // PerLevelStats — Player (all 1.0)
        per_level_stats_player_0: 1.0, per_level_stats_player_1: 1.0, per_level_stats_player_2: 1.0,
        per_level_stats_player_3: 1.0, per_level_stats_player_4: 1.0, per_level_stats_player_5: 1.0,
        per_level_stats_player_6: 1.0, per_level_stats_player_7: 1.0, per_level_stats_player_8: 1.0,
        per_level_stats_player_9: 1.0, per_level_stats_player_10: 1.0, per_level_stats_player_11: 1.0,
        // PerLevelStats — Wild Dino (vanilla 1.0)
        per_level_stats_dino_wild_0: 1.0, per_level_stats_dino_wild_1: 1.0, per_level_stats_dino_wild_2: 1.0,
        per_level_stats_dino_wild_3: 1.0, per_level_stats_dino_wild_4: 1.0, per_level_stats_dino_wild_5: 1.0,
        per_level_stats_dino_wild_6: 1.0, per_level_stats_dino_wild_7: 1.0, per_level_stats_dino_wild_8: 1.0,
        per_level_stats_dino_wild_9: 1.0,
        // PerLevelStats — Tamed Dino
        per_level_stats_dino_tamed_0: 0.2, per_level_stats_dino_tamed_1: 1.0, per_level_stats_dino_tamed_2: 1.0,
        per_level_stats_dino_tamed_3: 1.0, per_level_stats_dino_tamed_4: 1.0, per_level_stats_dino_tamed_5: 1.0,
        per_level_stats_dino_tamed_6: 1.0, per_level_stats_dino_tamed_7: 1.0, per_level_stats_dino_tamed_8: 0.17,
        per_level_stats_dino_tamed_9: 1.0,
        // PerLevelStats — Tamed Add
        per_level_stats_tamed_add_0: 0.14, per_level_stats_tamed_add_1: 1.0, per_level_stats_tamed_add_2: 1.0,
        per_level_stats_tamed_add_3: 1.0, per_level_stats_tamed_add_4: 1.0, per_level_stats_tamed_add_5: 1.0,
        per_level_stats_tamed_add_6: 1.0, per_level_stats_tamed_add_7: 1.0, per_level_stats_tamed_add_8: 0.14,
        per_level_stats_tamed_add_9: 1.0,
        // PerLevelStats — Tamed Affinity
        per_level_stats_dino_tamed_affinity_0: 0.44, per_level_stats_dino_tamed_affinity_1: 1.0,
        per_level_stats_dino_tamed_affinity_2: 1.0, per_level_stats_dino_tamed_affinity_3: 1.0,
        per_level_stats_dino_tamed_affinity_4: 1.0, per_level_stats_dino_tamed_affinity_5: 1.0,
        per_level_stats_dino_tamed_affinity_6: 1.0, per_level_stats_dino_tamed_affinity_7: 1.0,
        per_level_stats_dino_tamed_affinity_8: 0.44, per_level_stats_dino_tamed_affinity_9: 1.0,
    },

    // ─── PvE STANDARD + QUICK BREEDING ────────────────────────────────────────
    pve_standard_qb: {
        label: "PvE Standard + Quick Breeding",
        description: "PvE Standard mit Quick Breeding: ~38 min Ei, ~2h26min Auswachsen, 1 Imprint bei ~80 min = 100%. Vanilla Wild Dinos, 10x Taming.",
        tags: ["2x Farming", "10x Taming", "Quick Breeding", "Vanilla Wild Dinos"],
        // Difficulty — vanilla wild dino stats, vanilla damage
        difficulty_offset: 1.0,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.0,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 1.3,
        kill_xp_multiplier: 1.0,
        harvest_xp_multiplier: 1.0,
        craft_xp_multiplier: 1.0,
        generic_xp_multiplier: 1.0,
        special_xp_multiplier: 1.0,
        override_max_experience_points_player: 0,
        // Taming — 10x, vanilla damage
        taming_speed_multiplier: 10.0,
        tamed_dino_damage_multiplier: 1.0,
        tamed_dino_resistance_multiplier: 1.0,
        wild_dino_torpor_drain_multiplier: 1.0,
        wild_dino_character_food_drain_multiplier: 1.0,
        tamed_dino_torpor_drain_multiplier: 1.0,
        passive_tame_interval_multiplier: 1.0,
        disable_dino_riding: false,
        disable_dino_taming: false,
        use_tame_limit_for_structures_only: false,
        max_tamed_dinos: 8000,
        // Harvesting — 2x
        harvest_amount_multiplier: 2.0,
        harvest_health_multiplier: 2.0,
        resource_respawn_period_multiplier: 0.1,
        resource_no_replenish_radius_players: 0.3,
        resource_no_replenish_radius_structures: 0.4,
        player_harvesting_damage_multiplier: 1.0,
        dino_harvesting_damage_multiplier: 3.2,
        // Breeding — Quick Breeding (Giga-tuned)
        mating_interval_multiplier: 0.0001,
        mating_speed_multiplier: 40.0,
        lay_egg_interval_multiplier: 1.0,
        egg_hatch_speed_multiplier: 8.0,
        baby_mature_speed_multiplier: 75.0,
        baby_cuddle_interval_multiplier: 0.174,
        baby_imprinting_stat_scale_multiplier: 5.0,
        baby_imprint_amount_multiplier: 50.0,
        baby_food_consumption_speed_multiplier: 1.0,
        baby_cuddle_grace_period_multiplier: 5.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.2,
        player_character_food_drain_multiplier: 0.2,
        player_character_stamina_drain_multiplier: 1.0,
        player_character_health_recovery_multiplier: 1.0,
        dino_character_health_recovery_multiplier: 1.0,
        item_stack_size_multiplier: 1.0,
        global_spoiling_time_multiplier: 1.0,
        global_item_decomposition_time_multiplier: 1.0,
        global_corpse_decomposition_time_multiplier: 1.0,
        base_temperature_multiplier: 0.475,
        day_cycle_speed_scale: 1.0,
        day_time_speed_scale: 1.6,
        night_time_speed_scale: 3.0,
        kick_idle_players_period: 3600,
        show_map_player_location: true,
        allow_third_person_player: true,
        server_crosshair: true,
        global_voice_chat: false,
        proximity_chat: false,
        // Loot — 2.5x
        supply_crate_loot_quality_multiplier: 2.5,
        fishing_loot_quality_multiplier: 2.5,
        crafting_skill_bonus_multiplier: 1.0,
        allow_custom_recipes: true,
        custom_recipe_effectiveness_multiplier: 1.0,
        custom_recipe_skill_multiplier: 1.0,
        disable_loot_crates: false,
        random_supply_crate_points: false,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 3600.0,
        disable_structure_placement_collision: false,
        allow_platform_saddle_multi_floors: false,
        ignore_structures_prevention_volumes: true,
        genesis_use_structures_prevention_volumes: true,
        fast_decay_interval: 43200,
        structure_damage_repair_cooldown: 180,
        allow_cave_building_pve: false,
        allow_flyer_carry_pve_gus: false,
        disable_structure_decay_pve: false,
        pve_structure_decay_destruction_period: 1.0,
        max_structures_in_range: 6700,
        // Tribe & PvE
        server_pvp: false,
        max_tribe_size: 70,
        max_tribe_logs: 1,
        max_alliances_per_tribe: 10,
        disable_friendly_fire: false,
        pve_disable_friendly_fire: false,
        pve_allow_tribe_war: true,
        pve_allow_tribe_war_cancel: false,
        // Turrets
        limit_turrets_in_range: true,
        limit_turrets_range: 10000,
        limit_turrets_num: 100,
        hard_limit_turrets_in_range: true,
        passive_defenses_damage_riderless_dinos: false,
        dino_turret_damage_multiplier: 1.0,
        // Transfers
        no_tribute_downloads: false,
        prevent_download_survivors: false,
        prevent_download_items: false,
        prevent_download_dinos: false,
        // Genesis
        disable_genesis_missions: false,
        show_creative_mode: false,
        auto_unlock_all_engrams: false,
        // PerLevelStats — Player (all 1.0)
        per_level_stats_player_0: 1.0, per_level_stats_player_1: 1.0, per_level_stats_player_2: 1.0,
        per_level_stats_player_3: 1.0, per_level_stats_player_4: 1.0, per_level_stats_player_5: 1.0,
        per_level_stats_player_6: 1.0, per_level_stats_player_7: 1.0, per_level_stats_player_8: 1.0,
        per_level_stats_player_9: 1.0, per_level_stats_player_10: 1.0, per_level_stats_player_11: 1.0,
        // PerLevelStats — Wild Dino (vanilla 1.0)
        per_level_stats_dino_wild_0: 1.0, per_level_stats_dino_wild_1: 1.0, per_level_stats_dino_wild_2: 1.0,
        per_level_stats_dino_wild_3: 1.0, per_level_stats_dino_wild_4: 1.0, per_level_stats_dino_wild_5: 1.0,
        per_level_stats_dino_wild_6: 1.0, per_level_stats_dino_wild_7: 1.0, per_level_stats_dino_wild_8: 1.0,
        per_level_stats_dino_wild_9: 1.0,
        // PerLevelStats — Tamed Dino
        per_level_stats_dino_tamed_0: 0.2, per_level_stats_dino_tamed_1: 1.0, per_level_stats_dino_tamed_2: 1.0,
        per_level_stats_dino_tamed_3: 1.0, per_level_stats_dino_tamed_4: 1.0, per_level_stats_dino_tamed_5: 1.0,
        per_level_stats_dino_tamed_6: 1.0, per_level_stats_dino_tamed_7: 1.0, per_level_stats_dino_tamed_8: 0.17,
        per_level_stats_dino_tamed_9: 1.0,
        // PerLevelStats — Tamed Add
        per_level_stats_tamed_add_0: 0.14, per_level_stats_tamed_add_1: 1.0, per_level_stats_tamed_add_2: 1.0,
        per_level_stats_tamed_add_3: 1.0, per_level_stats_tamed_add_4: 1.0, per_level_stats_tamed_add_5: 1.0,
        per_level_stats_tamed_add_6: 1.0, per_level_stats_tamed_add_7: 1.0, per_level_stats_tamed_add_8: 0.14,
        per_level_stats_tamed_add_9: 1.0,
        // PerLevelStats — Tamed Affinity
        per_level_stats_dino_tamed_affinity_0: 0.44, per_level_stats_dino_tamed_affinity_1: 1.0,
        per_level_stats_dino_tamed_affinity_2: 1.0, per_level_stats_dino_tamed_affinity_3: 1.0,
        per_level_stats_dino_tamed_affinity_4: 1.0, per_level_stats_dino_tamed_affinity_5: 1.0,
        per_level_stats_dino_tamed_affinity_6: 1.0, per_level_stats_dino_tamed_affinity_7: 1.0,
        per_level_stats_dino_tamed_affinity_8: 0.44, per_level_stats_dino_tamed_affinity_9: 1.0,
    },

    // ─── INSTANT BREEDING (Background Overlay — Breeding Only) ────────────────
    instant_breeding: {
        label: "Instant Breeding",
        description: "Breeding-only overlay preset. Instant mating, ~38 sec egg, ~9 min mature, easy imprint.",
        // Mating — instant
        mating_interval_multiplier: 0.0001,
        mating_speed_multiplier: 40.0,
        lay_egg_interval_multiplier: 1.0,
        // Egg & maturation — 240x / 480x
        egg_hatch_speed_multiplier: 240.0,
        baby_mature_speed_multiplier: 480.0,
        // Imprint
        baby_cuddle_interval_multiplier: 0.1,
        baby_imprinting_stat_scale_multiplier: 5.0,
        baby_imprint_amount_multiplier: 10.0,
        baby_food_consumption_speed_multiplier: 1.0,
        baby_cuddle_grace_period_multiplier: 5.0,
        allow_anyone_baby_imprint_cuddle: true,
    },

    // ─── QUICK BREEDING (Background Overlay — Breeding Only) ──────────────────
    // Tuned for Giganotosaurus as reference dino.
    // Vanilla Giga: egg ~300 min, maturation ~10,920 min, cuddle interval ~461 min
    // At these settings:  egg ~37.5 min | mature ~145.6 min (2h 26min) | 1 cuddle at ~80 min
    quick_breeding: {
        label: "Quick Breeding",
        description: "Breeding-only overlay preset, tuned for Giganotosaurus as reference. ~38 min egg, ~2h26min mature, 1 imprint at ~80 min = 100%.",
        // Egg & maturation
        egg_hatch_speed_multiplier: 8.0,
        baby_mature_speed_multiplier: 75.0,
        // Food consumption — keep manageable
        baby_food_consumption_speed_multiplier: 1.0,
        // 1 cuddle per lifetime at ~80 min into growth (interval > half of 146 min maturation)
        // 461 min vanilla × 0.174 = ~80 min
        baby_cuddle_interval_multiplier: 0.174,
        // Grace period: generous so player has time to react
        baby_cuddle_grace_period_multiplier: 5.0,
        // 50x guarantees 100% imprint on any dino from a single cuddle
        baby_imprint_amount_multiplier: 50.0,
        baby_imprinting_stat_scale_multiplier: 5.0,
        allow_anyone_baby_imprint_cuddle: true,
        // Mating — instant
        mating_interval_multiplier: 0.0001,
        mating_speed_multiplier: 40.0,
        lay_egg_interval_multiplier: 1.0,
    },

    // ─── EASY PvE (Real ASA Server — User-Provided) ───────────────────────────
    easy_pve: {
        label: "Easy PvE (ASA)",
        description: "Real-world Easy PvE ASA server config. Very fast breeding, high taming speed, generous loot, mild climate.",
        // Difficulty
        difficulty_offset: 0.5,
        override_official_difficulty: 5.0,
        dino_damage_multiplier: 1.0,
        player_damage_multiplier: 1.2,
        dino_resistance_multiplier: 1.0,
        player_resistance_multiplier: 1.0,
        // XP
        xp_multiplier: 1.3,
        kill_xp_multiplier: 1.0,
        harvest_xp_multiplier: 1.0,
        craft_xp_multiplier: 1.0,
        generic_xp_multiplier: 1.0,
        special_xp_multiplier: 1.0,
        override_max_experience_points_player: 0,
        // Taming
        taming_speed_multiplier: 10.0,
        tamed_dino_damage_multiplier: 2.0,
        tamed_dino_resistance_multiplier: 1.0,
        wild_dino_torpor_drain_multiplier: 1.0,
        wild_dino_character_food_drain_multiplier: 1.0,
        tamed_dino_torpor_drain_multiplier: 1.0,
        passive_tame_interval_multiplier: 1.0,
        disable_dino_riding: false,
        disable_dino_taming: false,
        use_tame_limit_for_structures_only: false,
        max_tamed_dinos: 8000,
        max_tamed_dinos_gus: 8000,
        // Harvesting
        harvest_amount_multiplier: 1.1,
        harvest_health_multiplier: 2.0,
        resource_respawn_period_multiplier: 0.1,
        resource_no_replenish_radius_players: 0.3,
        resource_no_replenish_radius_structures: 0.4,
        player_harvesting_damage_multiplier: 1.0,
        dino_harvesting_damage_multiplier: 3.2,
        // Breeding
        mating_interval_multiplier: 0.0001,
        mating_speed_multiplier: 40.0,
        lay_egg_interval_multiplier: 1.0,
        egg_hatch_speed_multiplier: 240.0,
        baby_mature_speed_multiplier: 480.0,
        baby_cuddle_interval_multiplier: 0.1,
        baby_imprinting_stat_scale_multiplier: 5.0,
        baby_imprint_amount_multiplier: 10.0,
        baby_food_consumption_speed_multiplier: 1.0,
        baby_cuddle_grace_period_multiplier: 5.0,
        allow_anyone_baby_imprint_cuddle: true,
        // QoL
        player_character_water_drain_multiplier: 0.2,
        player_character_food_drain_multiplier: 0.2,
        player_character_stamina_drain_multiplier: 1.0,
        player_character_health_recovery_multiplier: 1.0,
        dino_character_health_recovery_multiplier: 1.0,
        item_stack_size_multiplier: 1.0, // handled by TG Stacking Mod
        global_spoiling_time_multiplier: 1.0,
        global_item_decomposition_time_multiplier: 1.0,
        global_corpse_decomposition_time_multiplier: 1.0,
        base_temperature_multiplier: 0.475,
        day_cycle_speed_scale: 1.0,
        day_time_speed_scale: 1.6,
        night_time_speed_scale: 3.0,
        kick_idle_players_period: 3600,
        show_map_player_location: true,
        allow_third_person_player: true,
        server_crosshair: true,
        global_voice_chat: false,
        proximity_chat: false,
        // Loot
        supply_crate_loot_quality_multiplier: 3.0,
        fishing_loot_quality_multiplier: 3.0,
        crafting_skill_bonus_multiplier: 1.0,
        allow_custom_recipes: true,
        custom_recipe_effectiveness_multiplier: 1.0,
        custom_recipe_skill_multiplier: 1.0,
        disable_loot_crates: false,
        random_supply_crate_points: false,
        // Building
        allow_structure_pickup: true,
        structure_pickup_time_after_placement: 3600.0,
        disable_structure_placement_collision: false,
        allow_platform_saddle_multi_floors: false,
        ignore_structures_prevention_volumes: true,
        genesis_use_structures_prevention_volumes: true,
        fast_decay_interval: 43200,
        structure_damage_repair_cooldown: 180,
        allow_cave_building_pve: false,
        allow_flyer_carry_pve_gus: false,
        disable_structure_decay_pve: false,
        pve_structure_decay_destruction_period: 1.0,
        max_structures_in_range: 6700,
        // Tribe & PvE
        server_pvp: false,
        max_tribe_size: 70,
        max_tribe_logs: 1,
        max_alliances_per_tribe: 10,
        disable_friendly_fire: false,
        pve_disable_friendly_fire: false,
        pve_allow_tribe_war: true,
        pve_allow_tribe_war_cancel: false,
        // Turrets
        limit_turrets_in_range: true,
        limit_turrets_range: 10000,
        limit_turrets_num: 100,
        hard_limit_turrets_in_range: true,
        passive_defenses_damage_riderless_dinos: false,
        dino_turret_damage_multiplier: 1.0,
        // Transfers
        no_tribute_downloads: false,
        prevent_download_survivors: false,
        prevent_download_items: false,
        prevent_download_dinos: false,
        // Genesis
        disable_genesis_missions: false,
        show_creative_mode: false,
        auto_unlock_all_engrams: false,
        // PerLevelStats — Player (all 1.0)
        per_level_stats_player_0: 1.0, per_level_stats_player_1: 1.0, per_level_stats_player_2: 1.0,
        per_level_stats_player_3: 1.0, per_level_stats_player_4: 1.0, per_level_stats_player_5: 1.0,
        per_level_stats_player_6: 1.0, per_level_stats_player_7: 1.0, per_level_stats_player_8: 1.0,
        per_level_stats_player_9: 1.0, per_level_stats_player_10: 1.0, per_level_stats_player_11: 1.0,
        // PerLevelStats — Wild Dino (all 0.5 — easier wilds)
        per_level_stats_dino_wild_0: 0.5, per_level_stats_dino_wild_1: 0.5, per_level_stats_dino_wild_2: 0.5,
        per_level_stats_dino_wild_3: 0.5, per_level_stats_dino_wild_4: 0.5, per_level_stats_dino_wild_5: 0.5,
        per_level_stats_dino_wild_6: 0.5, per_level_stats_dino_wild_7: 0.5, per_level_stats_dino_wild_8: 0.5,
        per_level_stats_dino_wild_9: 0.5,
        // PerLevelStats — Tamed Dino
        per_level_stats_dino_tamed_0: 0.2, per_level_stats_dino_tamed_1: 1.0, per_level_stats_dino_tamed_2: 1.0,
        per_level_stats_dino_tamed_3: 1.0, per_level_stats_dino_tamed_4: 1.0, per_level_stats_dino_tamed_5: 1.0,
        per_level_stats_dino_tamed_6: 1.0, per_level_stats_dino_tamed_7: 1.0, per_level_stats_dino_tamed_8: 0.17,
        per_level_stats_dino_tamed_9: 1.0,
        // PerLevelStats — Tamed Add
        per_level_stats_tamed_add_0: 0.14, per_level_stats_tamed_add_1: 1.0, per_level_stats_tamed_add_2: 1.0,
        per_level_stats_tamed_add_3: 1.0, per_level_stats_tamed_add_4: 1.0, per_level_stats_tamed_add_5: 1.0,
        per_level_stats_tamed_add_6: 1.0, per_level_stats_tamed_add_7: 1.0, per_level_stats_tamed_add_8: 0.14,
        per_level_stats_tamed_add_9: 1.0,
        // PerLevelStats — Tamed Affinity
        per_level_stats_dino_tamed_affinity_0: 0.44, per_level_stats_dino_tamed_affinity_1: 1.0,
        per_level_stats_dino_tamed_affinity_2: 1.0, per_level_stats_dino_tamed_affinity_3: 1.0,
        per_level_stats_dino_tamed_affinity_4: 1.0, per_level_stats_dino_tamed_affinity_5: 1.0,
        per_level_stats_dino_tamed_affinity_6: 1.0, per_level_stats_dino_tamed_affinity_7: 1.0,
        per_level_stats_dino_tamed_affinity_8: 0.44, per_level_stats_dino_tamed_affinity_9: 1.0,
    },
};

// Get preset by experience + mode
export function getPreset(experience, mode) {
    const key = `${experience}_${mode}`;
    return PRESETS[key] || PRESETS["intermediate_pve"];
}

// Get all preset keys
export function getPresetKeys() {
    return Object.keys(PRESETS);
}
